server-version-supported: "1.21x"
cooldown-seconds: 60

cooldowns:
  Enderman Card:
    left: 60
    right: 40
    shift_right: 90
  Zombie Card:
    left: 60
    right: 40
    shift_right: 90
  Creeper Card:
    left: 60
    right: 90
    shift_right: 120
  Warden Card:
    left: 60
    right: 120
    shift_right: 60
  Lighting Card:
    left: 40
    right: 20
    shift_right: 60
  Ghost Card:
    left: 60
    right: 40
    shift_right: 90

zombie-card:
  max-zombies: 2
  duration-seconds: 60

first-join:
  give-random-card: true
  allowed-cards:
    - Enderman
    - Herobrine
    - Nothing
    - Zombie
    - Warden
    - Creeper
    - Lighting
    - Ghost
    - Ruin
  allow-ultimate-on-join: false

drops:
  natural-death-drops-card: false
  drop-only-if-killed-by-player: true

recipes:
  ultimate-card:
    enabled: true
    require-all-9: true

storage-file: playerdata.yml
