server-version-supported: "1.21.11"
cooldown-seconds: 60         # default global cooldown (changeable per-card below)
cards:
  Enderman:
    cooldown: 60
  Herobrine:
    cooldown: 120
  Nothing:
    cooldown: 40
  Zombie:
    cooldown: 130
  Warden:
    cooldown: 50
  Creeper:
    cooldown: 100
  Lighting:
    cooldown: 40
  Ghost:
    cooldown: 45
  Ruin:
    cooldown: 20
  Unlimited:
    cooldown: 200

first-join:
  give-random-card: true
  allowed-cards:
    - Enderman
    - Herobrine
    - Nothing
    - Zombie
    - Warden
    - Creeper
    - Lighting
    - Ghost
    - Ruin
  allow-unlimited-on-join: false

drops:
  natural-death-drops-card: false
  drop-only-if-killed-by-player: true

recipes:
  unlimited-card:
    enabled: true
    require-all-9: true

storage-file: playerdata.yml
